export const columns = [
  { field: "id", headerName: "ID", width: 33 },
  { field: "registraiId", headerName: "Registrai Id" },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    cellClassName: "name-column--cell",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "left",
    align: "left",
    width: 44,
  },
  { field: "phone", headerName: "Phone Number", flex: 1 },
  { field: "email", headerName: "Email", flex: 1 },
  { field: "address", headerName: "Address", flex: 1 },
  { field: "city", headerName: "City", flex: 1 },
  { field: "zipCode", headerName: "Zip Code" },
];

export const rows = [
  {
    id: 1,
    name: "Jon Snow",
    email: "jonsnow@gmail.com",
    age: 35,
    phone: "(665)121-5454",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
  {
    id: 2,
    name: "Carsel Lannister",
    email: "carseilannister@gmail.com",
    age: 42,
    phone: "(421)341-2288",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
  {
    id: 3,
    name: "Jaime Lannister",
    email: "jaimelannister@gmail.com",
    age: 45,
    phone: "(422)982-6739",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
  {
    id: 4,
    name: "Riyan Adnan",
    email: "riyanadnan@gmail.com",
    age: 33,
    phone: "(967)777-8888",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
  {
    id: 5,
    name: "Sadaa Abdoalqui",
    email: "sadaaabdoalqui@gmail.com",
    age: 29,
    phone: "(967)777-9999",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
  {
    id: 6,
    name: "Ever Melisandre",
    email: "evermelisandre@gmail.com",
    age: 50,
    phone: "(232)545-6483",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
  {
    id: 7,
    name: "Ferrara Clifford",
    email: "ferraraclifford@gmail.com",
    age: 24,
    phone: "(543)124-8123",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
  {
    id: 8,
    name: "Rossini Frances",
    email: "rossinifrances@gmail.com",
    age: 16,
    phone: "(222)444-5555",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
  {
    id: 9,
    name: "Harvey Roxie",
    email: "harveyroxie@gmail.com",
    age: 65,
    phone: "(444)555-6239",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
  {
    id: 10,
    name: "Harvey Roxie",
    email: "harveyroxie@gmail.com",
    age: 15,
    phone: "(444)555-6239",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
  {
    id: 11,
    name: "Harvey Roxie",
    email: "harveyroxie@gmail.com",
    age: 19,
    phone: "(444)555-6239",
    address: "Taiz Street",
    city: "Sanaa",
    zipCode: "111234",
    registraiId: 928397,
  },
];
